on: 
  push:
    branches:
      - staging


name: Build and deploy
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - name: Update environments file
      env: 
        RVM_BASE_URL: ${{ secrets.RVM_BASE_URL }}
        RVM_SERVER_URL: ${{ secrets.RVM_SERVER_URL }}
      run: |
        ENVIRONMENTS_FILE="$GITHUB_WORKSPACE/src/environments/environment.stage.ts"
        sed -i "s#SERVER_URL#${RVM_SERVER_URL}#g" $ENVIRONMENTS_FILE
        sed -i "s#SERVER_BASE_URL#${RVM_BASE_URL}#g" $ENVIRONMENTS_FILE
        echo "$(cat $ENVIRONMENTS_FILE)"
    - name: Build the solution
      run: npm run-script build:stage
    - name: Deploy the solution
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        RVM_MACHINE: ${{ secrets.RVM_MACHINE }}
        RVM_USERNAME: ${{ secrets.RVM_USERNAME }}
      run: |
        DEPLOY_FOLDER="$GITHUB_WORKSPACE/dist/a/"
        SSH_PATH="$HOME/.ssh"
        mkdir "$SSH_PATH"
        echo "$DEPLOY_KEY" > "$SSH_PATH/deploy_key"
        chmod 600 "$SSH_PATH/deploy_key"
        sh -c "rsync -rvz --omit-dir-times -e 'ssh -i $SSH_PATH/deploy_key -o StrictHostKeyChecking=no' $DEPLOY_FOLDER $RVM_USERNAME@$RVM_MACHINE:/var/www/html/"